[package]
name = "rmpp_enhancer"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "_accelerator"
crate-type = ["cdylib"]
path = "rust/src/lib.rs"

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py39"] }
fast_image_resize = { version = "5.1", features = ["image"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
imageproc = { version = "0.25", default-features = false }
jpeg-encoder = "0.6"
